### ISSUE TITLE
No hands, no errors in a-frame 7.1

### ISSUE THREAD

**Issue by rserota** [openleap/aframe-leap-hands#21]
I pasted the 'usage' example into a simple a-frame scene.  It seems to work fine in older versions of a-frame, up to 6.0, but when I try it in a-frame 7.1, I can't see my hands. I also don't get any errors in the console, so I'm not really sure how to go about debugging this. 

Is this project still maintained? Is it even intended to work with newer versions of a-frame? 

Thanks!

**Comment by donmccurdy** [comment]
I just updated the dependencies and ran the examples, but things seem to be working in 7.1 for me. If you're using aframe-extras (which the "grabbing" demo does depend on) make sure you've updated to the latest version. Older versions of aframe-extras may not work with aframe 7.1.
