### ISSUE TITLE
Type error for enablePhysics: true

### ISSUE THREAD

**Issue by graphadvantage** [openleap/aframe-leap-hands#23]
Hi

I'm getting a type error using the grabbing example.

I'm using aframe 0.8.2, aframe-extras and aframe-system-physics

TypeError: this.physics.Phase is undefined[Learn More]

Any tips much appreciated!
Thanks
Michael

**Comment by donmccurdy** [comment]
Thanks, what version of aframe-extras and aframe-physics-system are you using? It's been a while since I've updated this so it may be (and probably is) out of sync, but that particular error sounds like one of the other dependencies may be older, too.

**Comment by donmccurdy** [comment]
This should be fixed on the latest release. :)
